get:
  summary: Site meter data
  description: Detailed information about the site specific meter
  security:
    - bearerAuth: []
  responses:
    '200':
      description: get:/meters/site response
      content:
        application/json:
          schema:
            type: object
          examples:
            example2:
              summary: Example 1
              externalValue: "https://raw.githubusercontent.com/vloschiavo/powerwall2/openapi/samples/meters.site.json"
    '401':
      $ref: '../../spec.yaml#/components/responses/Unauthorized'
    '403':
      $ref: '../../spec.yaml#/components/responses/Forbidden'